# default Certificate Authority (CA) configuration
# make a copy of this file in CodeFoundry's config/ directory
# cp config/ca.sample.yml config/ca.yml
# config/ca.yml is listed in CodeFoundry's .gitignore

ca:
  name: codefoundry_ca                        # name of the cert CA
  common_name: codefoundry_ca                 # the IP or DNS name of the server that CodeFoundry is running on
  organization: CodeFoundry                   # name of the CA's organization
  organizational_unit: CodeFoundry            # sub-unit of the CA's organizations
  locality: ""                                # city or area name
  state: Maryland                             # state's name or its two-letter abbreviation (Maryland || MD)
  country: US                                 # two-letter country code (US)
  email_address: codefoundry@codefoundry.com  # not a required field in certificate_authority
  signing_entity: true                        # MUST BE SET TO TRUE IN ORDER TO SIGN USER CERTS USING THIS CA
  serial_number: 1                            # CA certificate is the root certificate so its serial number is 1
  public_key_file: /etc/apache2/ssl/certs/ca_sample.cert.pem
  private_key_file: /etc/apache2/ssl/private/ca_sample.key.pem
  dn: codefoundry_dn

codefoundry_ca:
  dir: /etc/apache2/ssl
  serial: /etc/apache2/ssl/ca/serial
  database: /etc/apache2/ssl/ca/index.txt
  new_certs_dir: /etc/apache2/ssl/certs
  certificate: /etc/apache2/ssl/certs/ca_sample.cert.pem
  private_key: /etc/apache2/ssl/private/ca_sample.key.pem
  default_days: 3650
  default_md: md5
  preserve: no
  email_in_dn: yes
  policy: ca_policy_match
  
codefoundry_dn:
  organization: CodeFoundry